### ISSUE TITLE
class Rules

### ISSUE THREAD

**Issue by gisellemnr** [natvern/CCLITP#3]
This class is technically a calculus. It should contain only the functions corresponding to inference rules of a calculus. From the outside, these functions should behave as follows:

- Take a sequent and main formula as input
- Return a list of sequents (premises) as the output.

There are different ways the main formula can be indicated: either by passing the actual formula, or its position, for example.

Each rule is applied to one side of the sequent. One option is to have one function for each side and connective. Another option is to have one rule for each connective, and have the side passed as a parameter. I like the first option better because it will look closer to the calculus we see in a book, and thus easier to verify that it is implementing what it is supposed to.

**Comment by natvern** [comment]
Fixed on 54121c337148c4f60faf7aac71f23db5721d46d5.
