### ISSUE TITLE
class Formula

### ISSUE THREAD

**Issue by gisellemnr** [natvern/CCLITP#4]
The formula class is technically encoding a sequent. Also, there are a lot of things happening there. I would suggest separating:
- what is a sequent
- what is a proof tree

The proof tree part (or class) would be responsible for keeping track of open goals and replacing them by subgoals upon applications of rules (i.e. calls to functions from a calculus class).

The sequent part (or class) would define how you internally represent a sequent (pair of list? pair of sets?) and possibly simple functions that manipulate it as needed.

**Comment by natvern** [comment]
Fixed on 54121c337148c4f60faf7aac71f23db5721d46d5.
